version: "3"
services:
  customer:
    image: bcgovimages/aries-cloudagent:py3.9-indy-1.16.0_0.10.4
    container_name: customer
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://customer:5100"
      ACAPY_LABEL: "customer"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_GENESIS_URL: "http://test.bcovrin.vonx.io/genesis"
      ADMIN_PORT: "5000"
      AGENT_PORT: "5100"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 5000 \
        --inbound-transport http '0.0.0.0' 5100 \
        --outbound-transport http  \
        --wallet-type askar \
        --wallet-name tub-wallet \
        --wallet-key tub-key \
        --preserve-exchange-records \
        --auto-provision \
        --public-invites \
        --seed Dissident2_Client_---_0000000000 \
        --auto-respond-credential-proposal \
        --auto-respond-credential-offer \
        --auto-respond-credential-request \
        --auto-respond-presentation-proposal \
        --auto-respond-presentation-request \
        --auto-store-credential \
        --auto-verify-presentation \
        --preserve-exchange-records \
        --log-level INFO \
        --auto-ping-connection \
        --public-invites \
        --requests-through-public-did \
        --webhook-url http://130.149.223.197:5555/webhook"
    ]
    ports:
      - "5000:5000"
      - "5100:5100"

  provider:
    image: bcgovimages/aries-cloudagent:py3.9-indy-1.16.0_0.10.4
    container_name: provider
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://provider:6100"
      ACAPY_LABEL: "provider"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_GENESIS_URL: "http://test.bcovrin.vonx.io/genesis"
      ADMIN_PORT: "6000"
      AGENT_PORT: "6100"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 6000 \
        --inbound-transport http '0.0.0.0' 6100 \
        --outbound-transport http  \
        --wallet-type askar \
        --wallet-name tub-wallet \
        --wallet-key tub-key \
        --preserve-exchange-records \
        --auto-provision \
        --public-invites \
        --seed Dissident2_Provider_---_00000000 \
        --auto-respond-credential-proposal \
        --auto-respond-credential-offer \
        --auto-respond-credential-request \
        --auto-respond-presentation-proposal \
        --auto-respond-presentation-request \
        --auto-store-credential \
        --auto-verify-presentation \
        --preserve-exchange-records \
        --log-level INFO \
        --auto-ping-connection \
        --public-invites \       
        --requests-through-public-did \
        --webhook-url http://130.149.223.197:6666/webhook"
    ]
    ports:
      - "6000:6000"
      - "6100:6100"
      
  ap:
    image: bcgovimages/aries-cloudagent:py3.9-indy-1.16.0_0.10.4
    container_name: ap
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://ap:7100"
      ACAPY_LABEL: "ap"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_GENESIS_URL: "http://test.bcovrin.vonx.io/genesis"
      ADMIN_PORT: "7000"
      AGENT_PORT: "7100"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 7000 \
        --inbound-transport http '0.0.0.0' 7100 \
        --outbound-transport http  \
        --wallet-type askar \
        --wallet-name tub-wallet \
        --wallet-key tub-key \
        --preserve-exchange-records \
        --auto-provision \
        --public-invites \
        --seed Dissident2_Ap_---_00000000000000 \
        --auto-respond-credential-proposal \
        --auto-respond-credential-offer \
        --auto-respond-credential-request \
        --auto-respond-presentation-proposal \
        --auto-respond-presentation-request \
        --auto-store-credential \
        --auto-verify-presentation \
        --preserve-exchange-records \
        --log-level INFO \
        --auto-ping-connection \
        --public-invites \
        --requests-through-public-did \
        --webhook-url http://130.149.223.197:7777/webhook"
    ]
    ports:
      - "7000:7000"
      - "7100:7100"

  dlg:
    image: bcgovimages/aries-cloudagent:py3.9-indy-1.16.0_0.10.4
    container_name: dlg
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://dlg:8100"
      ACAPY_LABEL: "dlg"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_GENESIS_URL: "http://test.bcovrin.vonx.io/genesis"
      ADMIN_PORT: "8000"
      AGENT_PORT: "8100"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 8000 \
        --inbound-transport http '0.0.0.0' 8100 \
        --outbound-transport http  \
        --wallet-type askar \
        --wallet-name tub-wallet \
        --wallet-key tub-key \
        --preserve-exchange-records \
        --auto-provision \
        --public-invites \
        --seed Dissident2_Dlg_---_0000000000000 \
        --auto-respond-credential-proposal \
        --auto-respond-credential-offer \
        --auto-respond-credential-request \
        --auto-respond-presentation-proposal \
        --auto-respond-presentation-request \
        --auto-store-credential \
        --auto-verify-presentation \
        --preserve-exchange-records \
        --log-level INFO \
        --auto-ping-connection \
        --public-invites \
        --requests-through-public-did \
        --webhook-url http://130.149.223.197:8888/webhook"
    ]
    ports:
      - "8000:8000"
      - "8100:8100"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: walletuser
      POSTGRES_PASSWORD: walletpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  postgres-new:
    image: postgres:latest
    container_name: postgres-new
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: walletuser
      POSTGRES_PASSWORD: walletpassword
    volumes:
      - postgres_data_new:/var/lib/postgresql/data
    ports:
      - "5433:5432"
      
  issuer:
    image: bcgovimages/aries-cloudagent:py3.9-indy-1.16.0_0.10.4
    container_name: issuer
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://issuer:9100"
      ACAPY_LABEL: "issuer"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_GENESIS_URL: "http://test.bcovrin.vonx.io/genesis"
      ADMIN_PORT: "9000"
      AGENT_PORT: "9100"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 9000 \
        --inbound-transport http '0.0.0.0' 9100 \
        --outbound-transport http  \
        --wallet-type askar \
        --wallet-name tub-wallet \
        --wallet-key tub-key \
        --preserve-exchange-records \
        --auto-provision \
        --public-invites \
        --seed Dissident2_Issuer_---_0000000000 \
        --auto-respond-credential-proposal \
        --auto-respond-credential-offer \
        --auto-respond-credential-request \
        --auto-respond-presentation-proposal \
        --auto-respond-presentation-request \
        --auto-store-credential \
        --auto-verify-presentation \
        --preserve-exchange-records \
        --log-level INFO \
        --auto-ping-connection \
        --public-invites \
        --requests-through-public-did \
        --wallet-storage-type 'postgres_storage' \
        --wallet-storage-config '{\"url\":\"postgres:5432\",\"wallet_scheme\":\"MultiWalletSingleTable\", \"storage_config\":{\"url\":\"postgres:5432\",\"max_connections\":5,\"min_idle_time\":1,\"connection_timeout\":10}}' \
        --wallet-storage-creds '{\"account\":\"walletuser\",\"password\":\"walletpassword\",\"admin_account\":\"walletuser\",\"admin_password\":\"walletpassword\"}' \
        --webhook-url http://130.149.223.197:9999/webhook"
    ]
    ports:
      - "9000:9000"
      - "9100:9100"

  issuer2:
    image: bcgovimages/aries-cloudagent:py3.9-indy-1.16.0_0.10.4
    container_name: issuer2
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://issuer2:4100"
      ACAPY_LABEL: "issuer2"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_GENESIS_URL: "http://test.bcovrin.vonx.io/genesis"
      ADMIN_PORT: "4000"
      AGENT_PORT: "4100"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 4000 \
        --inbound-transport http '0.0.0.0' 4100 \
        --outbound-transport http  \
        --wallet-type askar \
        --wallet-name tub-wallet \
        --wallet-key tub-key \
        --preserve-exchange-records \
        --auto-provision \
        --public-invites \
        --seed Dissident2_Issuer2_---_000000000 \
        --auto-respond-credential-proposal \
        --auto-respond-credential-offer \
        --auto-respond-credential-request \
        --auto-respond-presentation-proposal \
        --auto-respond-presentation-request \
        --auto-store-credential \
        --auto-verify-presentation \
        --preserve-exchange-records \
        --log-level INFO \
        --auto-ping-connection \
        --public-invites \
        --requests-through-public-did \
        --wallet-storage-type 'postgres_storage' \
        --wallet-storage-config '{\"url\":\"postgres-new:5432\",\"wallet_scheme\":\"MultiWalletSingleTable\", \"storage_config\":{\"url\":\"postgres-new:5432\",\"max_connections\":5,\"min_idle_time\":1,\"connection_timeout\":10}}' \
        --wallet-storage-creds '{\"account\":\"walletuser\",\"password\":\"walletpassword\",\"admin_account\":\"walletuser\",\"admin_password\":\"walletpassword\"}' \
        --webhook-url http://130.149.223.213:4444/webhook"
    ]
    ports:
      - "4000:4000"
      - "4100:4100"


volumes:
  postgres_data:
  postgres_data_new: